import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import prettier from 'prettier';
import Package from './package.json' with { type: 'json' };
import RouteMap from './src/configuration/Routes.map.json' with { type: 'json' };

interface SitemapObject {
	description: string;
	label: string;
	href: string;
}

const Map: Array<SitemapObject> = RouteMap;
const XMLArray: Array<string> = [];
const Hostname: string = process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : Package.homepage;

const __filename = url.fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const publicDirectory = path.join(__dirname, 'public');

const PrettierConfig: prettier.Options = {
	parser: 'typescript',
	arrowParens: 'always',
	bracketSameLine: true,
	bracketSpacing: true,
	endOfLine: 'crlf',
	htmlWhitespaceSensitivity: 'css',
	jsxSingleQuote: true,
	printWidth: 120,
	proseWrap: 'preserve',
	quoteProps: 'as-needed',
	semi: true,
	tabWidth: 8,
	trailingComma: 'es5',
	useTabs: true,
};

function getDateString(date = new Date()) {
	return date.toISOString().slice(0, 10).replace(/-/g, '/');
}

(async () => {
	console.log('Generating sitemap.xml...');
	console.log('Using hostname', Hostname);

	for (const Route of Map) {
		XMLArray.push(`<url>
    <!-- Location Name: ${Route.label} -->
    <loc>${Hostname}${Route.href}</loc>
    <lastmod>${getDateString()}</lastmod>
    <changefreq>always</changefreq>
    <priority>0.7</priority>
</url>`);
		console.log(`Added ${Route.label} to sitemap`);
	}

	const XML = `<!-- Generated by Sitemap.ts by ninjaninja140. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${XMLArray.join('\n\n')}
</urlset>
`;

	console.log('Formatting sitemap...');
	const sitemapContent = await prettier.format(XML, {
		...PrettierConfig,
		parser: 'xml',
		plugins: ['@prettier/plugin-xml'],
	});
	console.log('Sitemap formatted successfully!');

	fs.writeFileSync(
		path.join(publicDirectory, './sitemap.xml'),
		'<?xml version="1.0" encoding="UTF-8"?>\n' + sitemapContent
	);
	console.log('Sitemap file generated successfully!');
})();
