// @ts-nocheck
// eslint-disable 
// prettier-ignore

// Generated by Vite Router
// https://www.npmjs.com/package/vite-plugin-router
// https://github.com/felipe-bergamaschi/vite-router

import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import type { RouteProps } from 'vite-plugin-router';

const R0 = lazy(() => import('./pages/contact'));
const R1 = lazy(() => import('./pages/'));
const R2 = lazy(() => import('./pages/ourStaff'));


/**
 * Generated by Vite Router
 *
 * @link https://www.npmjs.com/package/vite-plugin-router
 * @link https://github.com/felipe-bergamaschi/vite-router
 */
export function AppRoutes(props: RouteProps) {
  return (
    <BrowserRouter>
      <Suspense fallback={props.loadingPage || <div>Loading...</div>}>
        <Routes>
          <Route path={"/contact"} key={"/contact"} element={<R0></R0>}></Route>
<Route path={"/"} key={"/"} element={<R1></R1>}></Route>
<Route path={"/ourStaff"} key={"/ourStaff"} element={<R2></R2>}></Route>
          <Route
            path="*"
            element={props.notFoundPage || <div>404</div>}
          />
        </Routes>
      </Suspense> 
    </BrowserRouter>
  );
}