// Generated by Router.ts by ninjaninja140.

// Dependency Imports
import { createBrowserRouter, RouterProvider } from 'react-router-dom';

// Page Imports
import NotFound from '@components/NotFound';
import Index from '@pages/index';
import OurStaff from '@pages/ourStaff';

// Router Object
const router = createBrowserRouter([
	{
		path: '/',
		children: [
			{
				path: '/notfound',
				element: <NotFound Location='NotFound' Description={undefined} />,
				index: false,
			},
			{
				path: '/',
				element: <Index Location='Index' Description={undefined} />,
				index: true,
			},
			{
				path: '/our-staff',
				element: <OurStaff Location='Our Staff' Description={undefined} />,
				index: false,
			},
		],
	},
]);

// Router Exports
export default () => <RouterProvider router={router} />;
