// @ts-nocheck
// eslint-disable 
// prettier-ignore

// Generated by Vite Router
// https://www.npmjs.com/package/@bracketed/vite-plugin-router
// https://github.com/bracketed/vite-router

import type { Props } from '@bracketed/vite-plugin-router/types';
import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { Redirect } from '@bracketed/vite-plugin-router';

const R0 = lazy(() => import('./pages/about'));
const R1 = lazy(() => import('./pages/contact'));
const R2 = lazy(() => import('./pages/'));
const R3 = lazy(() => import('./pages/ourStaff'));


/**
 * Generated by Vite Router
 *
 * @link https://www.npmjs.com/package/@bracketed/vite-plugin-router
 * @link https://github.com/bracketed/vite-router
 */
export function AppRoutes(props: Props) {
  return (
    <BrowserRouter>
	<Suspense fallback={props.loadingPage || <div>Loading...</div>}>
        <Routes>
          <Route path={"/about-us"} key={"/about-us"} element={<R0></R0>}></Route>
<Route path={"/contact"} key={"/contact"} element={<R1></R1>}></Route>
<Route path={"/"} key={"/"} element={<R2></R2>}></Route>
<Route path={"/our-staff"} key={"/our-staff"} element={<R3></R3>}></Route>
		  <Route path={"/local"} key={"/local"} element={<Redirect href={"https://google.com"}/>}></Route>
		  <Route path="*" element={props.notFoundPage || <div>404</div>} />
        </Routes>
      </Suspense> 
    </BrowserRouter>
  );
}