// Generated by Router.ts by ninjaninja140.

// Dependency Imports
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import Unauthorised from "@components/Unauthorised";

// Page Imports
import NotFound from "@pages/NotFound";
import Index from "@pages/index";
import OurStaff from "@pages/ourStaff";

// Router Object
const router = createBrowserRouter([
	{
		path: "/",
		children: [
			{
				path: "*",
				element: (
					<NotFound
						Location='404 Not Found'
						Description={
							"The specified page could not be found on this website, maybe you typed it incorrectly?."
						}
					/>
				),
				index: false,
			},
			{
				path: "/",
				element: <Index Location='Index' Description={undefined} />,
				index: true,
			},
			{
				path: "/ourstaff",
				element: <OurStaff Location='OurStaff' Description={undefined} />,
				index: false,
			},
		],
	},
]);

// Router Exports
export default () => <RouterProvider router={router} />;
