// @ts-nocheck
// eslint-disable 
// prettier-ignore

// Generated by Vite Router
// https://www.npmjs.com/package/@bracketed/vite-plugin-router
// https://github.com/bracketed/vite-router

import type { Props } from '@bracketed/vite-plugin-router/types';
import { lazy, Suspense } from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';


const R0 = lazy(() => import('./pages/about'));
const R1 = lazy(() => import('./pages/careers/'));
const R2 = lazy(() => import('./pages/careers/jobs/[id]/apply'));
const R3 = lazy(() => import('./pages/careers/jobs/[id]/'));
const R4 = lazy(() => import('./pages/contact'));
const R5 = lazy(() => import('./pages/'));
const R6 = lazy(() => import('./pages/ourStaff'));


/**
 * Generated by Vite Router
 *
 * @link https://www.npmjs.com/package/@bracketed/vite-plugin-router
 * @link https://github.com/bracketed/vite-router
 */
export function AppRoutes(props: Props) {
  return (
    <BrowserRouter>
	<Suspense fallback={props.loadingPage || <div>Loading...</div>}>
        <Routes>
          <Route path={"/about-us"} key={"/about-us"} element={<R0></R0>}></Route>
<Route path={"/careers"} key={"/careers"} element={<R1></R1>}></Route>
<Route path={"/careers/jobs/:id/apply"} key={"/careers/jobs/:id/apply"} element={<R2></R2>}></Route>
<Route path={"/careers/jobs/:id"} key={"/careers/jobs/:id"} element={<R3></R3>}></Route>
<Route path={"/contact"} key={"/contact"} element={<R4></R4>}></Route>
<Route path={"/"} key={"/"} element={<R5></R5>}></Route>
<Route path={"/our-staff"} key={"/our-staff"} element={<R6></R6>}></Route>
		  
		  <Route path="*" element={props.notFoundPage || <div>404</div>} />
        </Routes>
      </Suspense> 
    </BrowserRouter>
  );
}